### ISSUE TITLE
Improve types. 

### ISSUE THREAD

**Issue by oSethoum** [macaron-css/macaron#12]
Auto complete doesn't seem to get the right object keys in the theme contract, is this intentional? 
![image](https://user-images.githubusercontent.com/88779394/206925216-392d1cd6-c640-4c03-aaf6-09c8db2b9f0a.png)

**Comment by Mokshit06** [comment]
Hi, the reason autocomplete isn't working is because `createTheme` has 2 overloads, `createTheme(vars, debugId)` and `createTheme(contract, vars, debugId)`, and typescript isn't sure which overload you're using and can't show suggestions because of that.
You can make it work by either adding a comma after the object like `createTheme(contract, {},)` or by passing an empty string as the third argument
