### ISSUE TITLE
vite lib mode/vite-dts build errors

### ISSUE THREAD

**Issue by zwagnr** [macaron-css/macaron#14]
I am currently in the processes of porting over a design system from Vanilla Extract to Macaron.

I was compiling with Vite in Lib mode using vite-dts in Vanilla Extract and everything was working fine. When using Macaron, the builds are failing.

![viteissue](https://user-images.githubusercontent.com/86675944/207990293-2e63e121-5636-4fce-9690-82fb7f224b55.png)

Here's the vite.config
```tsx
import { defineConfig } from 'vite';
import dts from 'vite-plugin-dts';
import { peerDependencies } from './package.json';
import { macaronVitePlugin } from '@macaron-css/vite';

const externals = [...Object.keys(peerDependencies)];

export default defineConfig({
  build: {
    lib: {
      entry: 'src/index.ts',
      fileName: 'index',
      formats: ['cjs', 'es'],
    },
    rollupOptions: {
      external: externals,
    },
  },
  plugins: [
    macaronVitePlugin(),
    dts({
      beforeWriteFile: (filePath, content) => ({
        content,
        filePath: filePath.replace('src', ''),
      }),
      compilerOptions: {
        baseUrl: './src/',
        emitDeclarationOnly: true,
        noEmit: false,
      },
      exclude: ['src/**/*.stories.tsx'],
      outputDir: 'dist/types',
    }),
  ],
});
```

FWIW, I was able to get builds working by removing vite-dts from the vite.config, building, and then running a separate build step with tsc and the following flags "tsc --emitDeclarationOnly --declaration --declarationDir dist/types".

**Comment by Mokshit06** [comment]
I believe this is something that's occurring because `extracted_*.css` files don't actually exist in the file system. They are virtual and are created and resolved by macaron's bundler plugins, but typescript is unable to resolve them.
This isn't something that can be fixed since we can't make ts resolve the virtual files, so removing vite-dts and running tsc as a different process is probably the only way to make it work
