### ISSUE TITLE
Is it possible to support the responsive variants approach from Stitches?

### ISSUE THREAD

**Issue by cetchebarne** [macaron-css/macaron#45]
We are working on a component library that uses Stitches, and analyzing alternatives we found this great library. I'm now making a POC to see if it covers all our use cases. 

The particular case I want to cover now is using responsive variants, so for something like this:

```
const Box = styled("div", {
  variants: { d: { flex: { display: "flex" }, grid: { display: "grid" } } },
});
```

We usually do:

`<Box d={{ '@initial': 'flex', '@md': 'grid'}} />`

Would it be possible to support this API? If not, what would be the best way to accomplish the same?

My understanding right now is that I would need to avoid using the `styled` API with the variants inside and replace it by Sprinkles from VE, but I'm wondering if there is something I'm missing.

Thanks.

**Comment by Mokshit06** [comment]
Hey! So supporting responsive variants is something that macaron doesn't currently support, due to the fact that it also couples runtime style insertion, and macaron's main aim is to move style generation to compile time.
One way to do this, something that can be added to macaron as well in the future, is to use [`window.matchMedia` API](https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia) and check if it is matching the breakpoint, something like:

```js
function getScreen() {
   if (window.matchMedia("(max-width: 768px)")) {
     return "sm";
   } else if  (window.matchMedia("(max-width: 1024px)")) {
     return "md"
   } else {
     return "lg";
   }
} 

const screenSize = getScreenSize();
<Box d={screenSize == 'md' ? 'grid' : 'flex'} />
```
