### ISSUE TITLE
Types not working for Solid

### ISSUE THREAD

**Issue by aryzing** [macaron-css/macaron#58]
Seems the types are not working for `@macaron-css/solid` v1.5.1. I'm not getting any intellisense with v1.5.1. Is there something missing here?

[simplescreenrecorder-2024-03-24_19.54.20.webm](https://github.com/macaron-css/macaron/assets/4924405/f9f9cbfc-13b6-4670-9b68-a19eb5f08b91)

**Comment by Mokshit06** [comment]
Ah yeah, the current SolidJS adapter doesn't have proper typings to support autocomplete, but it should be relatively easy to port over from React adapter. Can you open a PR doing that? If not, I will be able to fix it this week.

**Comment by aryzing** [comment]
Appreciate the encouragement, although I'm in the process of evaluating CSS libs and don't have the bandwidth to fix the issues I find with them

**Comment by PalmDevs** [comment]
> Ah yeah, the current SolidJS adapter doesn't have proper typings to support autocomplete, but it should be relatively easy to port over from React adapter.

What types are currently missing? Maybe I can help.

**Comment by Mokshit06** [comment]
Actually I was wrong. The types *DO* already work. @aryzing Can you try restarting your TS server maybe? A few more questions:

- Is this a JS file or TS?
- Do you have a tsconfig.json?

**Comment by aryzing** [comment]
I must be doing something wrong then, because the types are just now showing for me. I'll upload a reproduction repo soon.

[simplescreenrecorder-2024-04-12_16.50.51.webm](https://github.com/macaron-css/macaron/assets/4924405/b952c26c-c186-4bff-aa8d-e457624e806d)

**Comment by Mokshit06** [comment]
Found the issue! So the way macaron's solid and react adapter were implementing the type definitions was through vanilla-extract's internal types that were being accessed from the `/dist` directory of the package. This worked fine when `"moduleResolution"` in `tsconfig.json` was set to `"node"`, but when it's set to latest versions like `"bundler"` or `"nodenext"`, Typescript gives more importance to the `"exports"` in `package.json`, and vanilla-extract didn't export files from the `/dist` directory there.

Since the example you had was indeed using `"bundler"`, Typescript wasn't able to source the internal type defs.

This has been fixed in `v1.5.2` now! Macaron now implements the type defs by itself.

**Comment by aryzing** [comment]
That's great, thank you!

**Comment by PalmDevs** [comment]
@Mokshit06 Hi there, the issue seems to still be present in `1.5.2`. For whatever reason, the published types still uses the wrong import in `index.d.ts` file, but not in `index.d.mts` file. Could you look into this?

![The issue](https://github.com/macaron-css/macaron/assets/67689562/b6cbb00c-e8e7-46a5-9fe7-02feea5c32fa)

[Here's the link to the page.](https://www.npmjs.com/package/@macaron-css/solid?activeTab=code)

**Comment by Mokshit06** [comment]
Thanks for reporting this! Yeah I think I missed updating the exports in `package.json` to `index.d.mts`. Please update it to `v1.5.3` :)
